language: rust
rust:
  - stable

before_script: |
  rustup component add rustfmt &&
  rustup component add clippy &&
  rustup update nightly

script: |
  cargo +nightly check --all-targets --verbose &&
  cargo fmt -- --check &&
  cargo clippy -- -D clippy::all &&
  cargo build --verbose &&
  cargo test  --verbose
cache: cargo
